version: "2"
linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - revive
    - staticcheck
    - wrapcheck
  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
    wrapcheck:
      ignore-package-globs:
        - github.com/AitorConS/unikernel-engine/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - wrapcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
