[build]
lang = "raw"
disk_size = "512M"
# Mount point for the mysql data volume that --initialize-insecure seeds.
dirs = ["/var/lib/mysql"]

[program]
path = "mysqld"
args = [
  "--initialize-insecure",
  "--user=root",
  "--datadir=/var/lib/mysql",
]

[run]
memory = "512M"
